services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # BundleConfiguration
    Lukaschel\PimcoreRecaptchaBundle\Configuration\Configuration: ~

    # Lukaschel\PimcoreRecaptchaBundle\Tool\Install script
    Lukaschel\PimcoreRecaptchaBundle\Tool\Install:
        public: true
        calls:
            - [setConfiguration, ['@Lukaschel\PimcoreRecaptchaBundle\Configuration\Configuration']]

    # Lukaschel\PimcoreRecaptchaBundle event listener
    Lukaschel\PimcoreRecaptchaBundle\EventListener\RecaptchaListener:
        arguments: ['@service_container']
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: -109 }

    lukaschel.recaptcha:
        class: Lukaschel\PimcoreRecaptchaBundle\Components\Recaptcha
        public: true
        arguments:
            - '@service_container'